# Generated by Django 4.2.7 on 2024-11-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uplift", "0002_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
