# Generated by Django 4.2.16 on 2024-12-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uplift", "0004_inventoryitem_date_added_inventoryitem_date_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("Hygiene Items", "Hygiene Items"),
                    ("Canned Food", "Canned Food"),
                    ("Seasonal Clothing", "Seasonal Clothing"),
                    ("Basic Supplies", "Basic Supplies"),
                    ("Entertainment", "Entertainment"),
                    ("Others", "Others"),
                ],
                default="Others",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
